name: poker_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - jupyter
  - matplotlib
  - networkx
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - seaborn
  - tqdm
  - statsmodels
  - lxml
  - pytorch::pytorch=2.6.0
  - pytorch::pytorch-cuda=11.8
  - requests
  - beautifulsoup4
  - from ucimlrepo import fetch_ucirepo 
  - pip
  - pip:
    - torch-geometric
    - treys