name: poker_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - jupyter
  - matplotlib
  - networkx
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - tqdm
  - statsmodels
  - lxml
  - pytorch::pytorch=2.5.1
  - pytorch::cpuonly
  - requests
  - beautifulsoup4
  - pip
  - pip:
    - torch-geometric
    - treys