class_weights_path: ./data/uc_irvine/class_weights.pt
data:
  X_path: ./data/uc_irvine/X.csv
  test_size: 0.6
  y_path: ./data/uc_irvine/y.csv
dataloader:
  batch_size: 512
  num_workers: 10
  pin_memory: true
model:
  params:
    card_emb_dim: 16
    edge_attr_dim: 2
    hidden_dim: 16
    out_dim: 16
  save_dir: ./model_weights/hand_rank_predictor
  weights_path: ''
results:
  save_dir: ./training_results/hand_rank_predictor
training:
  device: cuda
  epochs: 200
  optimizer:
    lr: 0.0005
    type: AdamW
    weight_decay: 0.01
  save_interval: 30
  save_weights: true
  scheduler:
    gamma: 0.1
    step_size: 100
    type: StepLR
    use_scheduler: true
  start_epoch: 0
