
data:
  X_path: "./data/uc_irvine/X.csv"
  y_path: "./data/uc_irvine/y.csv"
  test_size: 0.6

dataloader:
  batch_size: 512
  num_workers: 10
  pin_memory: true

training:
  optimizer:
    type: "Adam"
    lr: 0.0001
    weight_decay: 0.0

  scheduler:
    type: null
    step_size: null
    gamma: null
    use_scheduler: null

  device: "cuda"
  epochs: 90
  save_weights: true
  start_epoch: 270
  save_interval: 30
  val_during_training: false

model:
  params:
    card_emb_dim: 16
    hidden_dim: 16
    out_dim: 16
    edge_attr_dim: 2
  weights_path: "./model_weights/hand_rank_predictor/hand_rank_predictor270.pth"
  save_dir: "./model_weights/hand_rank_predictor"

results:
  save_dir: "./training_results/hand_rank_predictor/run3"

class_weights_path: "./data/uc_irvine/class_weights.pt"
